spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/socnetwDB
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
  profiles:
    active: default
  main:
    banner-mode: "off"