CREATE TABLE USERS
(
    USER_ID      NUMBER PRIMARY KEY,
    USER_NAME    NVARCHAR2(64),
    REAL_NAME    NVARCHAR2(64),
    EMAIL        NVARCHAR2(64),
    PHONE_NUMBER NVARCHAR2(64),
    BIRTH_DATE   TIMESTAMP,
    POST_ID      NUMBER,
    PASSWORD     NVARCHAR2(16)
);

CREATE TABLE POST
(
    POST_ID          NUMBER PRIMARY KEY,
    MESSAGE          NVARCHAR2(128),
    DATE_POSTED      TIMESTAMP,
    LOCATION         NVARCHAR2(128),
    USERS_TAGGED     NUMBER,
    USER_POSTED      NUMBER,
    USER_PAGE_POSTED NUMBER,
    CONSTRAINT USER_TARGET_FK FOREIGN KEY (USERS_TAGGED) REFERENCES USERS (USER_ID),
    CONSTRAINT USER_POSTED_FK FOREIGN KEY (USER_POSTED) REFERENCES USERS (USER_ID),
    CONSTRAINT USER_PAGE_POSTED_FK FOREIGN KEY (USER_PAGE_POSTED) REFERENCES USERS (USER_ID)
);

ALTER TABLE USERS
    ADD CONSTRAINT POST_FK FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID);

CREATE TABLE RELATIONSHIP
(
    USER_ID_FROM         NUMBER NOT NULL,
    USER_ID_TO           NUMBER NOT NULL,
    STATUS               NVARCHAR2(256),
    FRIENDS_REQUEST_DATE TIMESTAMP,
    CONSTRAINT FK_USER_ONE FOREIGN KEY (USER_ID_FROM) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_USER_TWO FOREIGN KEY (USER_ID_TO) REFERENCES USERS (USER_ID),
    CONSTRAINT PK_RELATIONSHIP PRIMARY KEY (USER_ID_FROM, USER_ID_TO)

);

CREATE TABLE USERS_POST
(
    USER_ID NUMBER,
    POST_ID NUMBER,
    CONSTRAINT USERS_POST_PK PRIMARY KEY (USER_ID, POST_ID),
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID)
);

CREATE TABLE MESSAGE
(
    MESSAGE_ID   NUMBER PRIMARY KEY,
    USER_FROM    NUMBER,
    USER_TO      NUMBER,
    DATE_SEND    TIMESTAMP,
    DATE_EDITED  TIMESTAMP,
    DATE_DELETED TIMESTAMP,
    DATE_READ    TIMESTAMP,
    TEXT         CLOB,
    CONSTRAINT USER_FROM_FK FOREIGN KEY (USER_FROM) REFERENCES USERS (USER_ID),
    CONSTRAINT USER_TO_FK FOREIGN KEY (USER_TO) REFERENCES USERS (USER_ID)
);

CREATE SEQUENCE USER1_SEQ
    MINVALUE 0
    MAXVALUE 99999999
    START
        WITH 0
    INCREMENT BY 1
    CACHE 10;

CREATE SEQUENCE POST_SEQ
    MINVALUE 0
    MAXVALUE 99999999
    START
        WITH 0
    INCREMENT BY 1
    CACHE 10;

CREATE SEQUENCE MESSAGE_SEQ
    MINVALUE 0
    MAXVALUE 99999999
    START
        WITH 0
    INCREMENT BY 1
    CACHE 10;
